name: Controllo automatico README

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Controlla se README contiene la parola sole
        run: |
          grep -q "sole" README.md
      - name: Controlla se README contiene la parola maggio
        run: |
          grep -q "maggio" README.md

